# Generated by Django 5.1a1 on 2024-05-31 01:48

import PubFunc.base_db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_time', PubFunc.base_db.DateTimeFieldFormat(auto_now_add=True, verbose_name='创建时间')),
                ('upd_time', PubFunc.base_db.DateTimeFieldFormat(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=True, verbose_name='是否有效')),
                ('account', models.CharField(max_length=255, unique=True, verbose_name='账户名称')),
                ('password', models.CharField(max_length=255, verbose_name='账户密码')),
                ('nickname', models.CharField(default='匿名', max_length=255, verbose_name='账户昵称')),
                ('email', models.CharField(max_length=255, verbose_name='个人邮箱')),
                ('sex', models.BooleanField(default=True, verbose_name='个人性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '账户信息',
                'verbose_name_plural': '账户信息',
                'db_table': 'user_info',
                'ordering': ['ID'],
            },
        ),
    ]
