# Generated by Django 5.1a1 on 2024-06-03 08:46

import PubFunc.base_db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackPageUrl',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_time', PubFunc.base_db.DateTimeFieldFormat(auto_now_add=True, verbose_name='创建时间')),
                ('upd_time', PubFunc.base_db.DateTimeFieldFormat(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=True, verbose_name='是否有效')),
                ('page_name', models.CharField(max_length=10, unique=True, verbose_name='页面名称')),
                ('page_url', models.CharField(max_length=255, verbose_name='页面链接')),
                ('page_level', models.IntegerField(default='匿名', max_length=255, verbose_name='页面级别')),
                ('parent_id', models.BigIntegerField(default=0, verbose_name='父级ID')),
            ],
            options={
                'verbose_name': '后台管理页面路由',
                'verbose_name_plural': '后台管理页面路由',
                'db_table': 'back_page_url',
                'ordering': ['ID'],
            },
        ),
    ]
