# Generated by Django 5.1a1 on 2024-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpageurl',
            name='page_level',
            field=models.IntegerField(default=0, verbose_name='页面级别'),
        ),
    ]
