# Generated by Django 5.1a1 on 2024-06-04 01:22

import PubFunc.base_db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0002_alter_backpageurl_page_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_time', PubFunc.base_db.DateTimeFieldFormat(auto_now_add=True, verbose_name='创建时间')),
                ('upd_time', PubFunc.base_db.DateTimeFieldFormat(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=True, verbose_name='是否有效')),
                ('statu_code', models.BigIntegerField(default=0, verbose_name='状态码')),
                ('inter_en', models.CharField(max_length=255, verbose_name='英文信息')),
                ('inter_ch', models.CharField(max_length=255, verbose_name='中文信息')),
                ('explain_inter_solu', models.CharField(max_length=255, verbose_name='搞怪信息')),
            ],
            options={
                'verbose_name': '状态码信息',
                'verbose_name_plural': '状态码信息',
                'db_table': 'status',
                'ordering': ['ID'],
            },
        ),
    ]
