# Generated by Django 5.1a1 on 2024-06-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0003_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='statu_code',
            field=models.BigIntegerField(unique=True, verbose_name='状态码'),
        ),
    ]
