# Generated by Django 5.1a1 on 2024-06-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0005_rename_explain_inter_solu_status_inter_solu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpageurl',
            name='page_name',
            field=models.CharField(max_length=5, unique=True, verbose_name='页面名称'),
        ),
    ]
